Firebase繋ぎこみ
sockbase/Sockbase pull request #17
Opened 2023-02-28 04:52 UTC by 10mocy

Related #15

2023-03-02 11:20 UTC, TinyKitten commented
@10mocy 数行しかまだ見てないけど、自分でコード変更の理由が分かりづらそう思ったら自分でGitHubの変更かコードにコメント欲しい
eslintのルールを書き換えた理由がわからんかったのといまのフェーズではもちろん関係ないけど開発チームの他の人間に響く設定の変更は多少慎重にしたい

2023-03-02 12:12 UTC, 10mocy commented
> @10mocy 数行しかまだ見てないけど、自分でコード変更の理由が分かりづらそう思ったら自分でGitHubの変更かコードにコメント欲しい eslintのルールを書き換えた理由がわからんかったのといまのフェーズではもちろん関係ないけど開発チームの他の人間に響く設定の変更は多少慎重にしたい

ok

ESLintのルールは以下を許容する様に変更した
- strict-boolean-expressions: 条件式を厳密に管理する必要がないと判断したため
- multiline-ternary: 三項演算子使用時、複数行時の改行を強制するため(１行にまとめると可読性が低くなる)

2023-03-02 23:30 UTC, TinyKitten requested changes
書き換えが必要そうな場所あるから確認して❤️

2023-03-02 23:30 UTC, TinyKitten commented on packages/client/src/hooks/useFirebase.ts
> +interface IUseFirebase {
ここで`interface`を使った理由って何？`type`でも同様に実装できそう

2023-03-02 23:30 UTC, TinyKitten commented on packages/client/src/hooks/useFirebase.ts
> +            throw e
[fix]
意味なさそう。エラーのstateに突っ込むのが常套手段。
対応必要そうだったらこのファイル全体で修正して❤️
あとエラー発生時処理が止まらないようであれば`try-catch-finally`使えば解決しそうな

2023-03-02 23:30 UTC, TinyKitten commented on packages/client/src/hooks/useFirebase.ts
> +        setUser(undefined)
[imo]
ここでundefinedを使った理由がわからない
```suggestion
        setUser(null)
```

2023-03-02 23:30 UTC, TinyKitten commented on packages/client/src/hooks/useFirebase.ts
> +            onIdTokenChanged(auth, (user) => {
[ask]
これuseEffectで使うならクリーンアップ関数必要にならない？

[fix]
もし上記の処理が必要なら普通にバグなので直して❤️

2023-03-02 23:30 UTC, TinyKitten commented on packages/client/src/hooks/useFirebase.ts
> +
[nits]
値とメソッドで空白行作ってグルーピングしてるならvscodeでは色変わるはずだしこの空白は必要？

2023-03-02 23:30 UTC, TinyKitten commented on packages/client/src/hooks/useFirebaseError.ts
> +    const parse: (errorMessage: string) => string =
[nits]
`parse`というよりかは`localize`な気がする

2023-03-02 23:30 UTC, TinyKitten commented on packages/client/src/libs/FirebaseApp.ts
> +  async () => {
[fix]
`await`ないなら`async`外して他のファイルの呼び出しも修正して

2023-03-03 01:50 UTC, 10mocy commented on packages/client/src/GlobalStyle.tsx
> +    border-bottom: 2px solid #c0c0c0;
わかる

2023-03-03 01:51 UTC, 10mocy commented on packages/client/src/GlobalStyle.tsx
> +    border-bottom: 2px solid #c0c0c0;
どっかでvarに突っ込んでたな……
適当なタイミングで置き換えます

2023-03-03 01:56 UTC, 10mocy commented on packages/client/src/hooks/useFirebase.ts
> +interface IUseFirebase {
TSではinterfaceが推奨されている
https://www.typescriptlang.org/docs/handbook/advanced-types.html#interfaces-vs-type-aliases

2023-03-03 01:58 UTC, 10mocy commented on packages/client/src/hooks/useFirebase.ts
> +            throw e
例外処理はリファクタのタイミングで書いていくので、一旦lintエラーにならないように書いてる

2023-03-03 02:00 UTC, TinyKitten commented on packages/client/src/hooks/useFirebase.ts
> +            throw e
コメントないとわからんでその意図...

2023-03-03 02:03 UTC, 10mocy commented on packages/client/src/hooks/useFirebase.ts
> +            throw e
TODO残すようにします

2023-03-03 11:25 UTC, TinyKitten approved these changes
えらい

2023-03-03 13:38 UTC, merged