ダッシュボードレイアウト作成
sockbase/Sockbase pull request #19
Opened 2023-02-28 06:10 UTC by 10mocy

Resolve #4
Need to review #2, #17 first

2023-02-28 11:19 UTC, 10mocy commented
close #18

2023-03-02 23:41 UTC, TinyKitten requested changes
いくつか直して

2023-03-02 23:41 UTC, TinyKitten commented on packages/client/src/components/Layout/Dashboard/Dashboard.tsx
> +      <StyledHeader><Logotype src={LogotypeSVG} alt="Sockbase Logotype" /></StyledHeader>
[fix]
やたらと`Styled`って名前使ってるけど実際必要なprefixじゃなかったら意味的な命名をしてほしい

2023-03-02 23:41 UTC, TinyKitten commented on packages/client/src/components/Layout/Dashboard/Sidebar.tsx
> +      {menu.map(i => <StyledSection key={i.sectionKey}>
[fix]
`i`はindexとして使われることが多いのでオブジェクトの名前に使うのは不自然だと思う
`item`とか`it`でいいんじゃない？

2023-03-02 23:41 UTC, TinyKitten commented on packages/client/src/components/Layout/Dashboard/Sidebar.tsx
> +            i.items.map(i =>
[fix]
シャドーイングしないで❤️

2023-03-03 01:47 UTC, 10mocy commented on packages/client/src/components/Layout/Dashboard/Dashboard.tsx
> +      <StyledHeader><Logotype src={LogotypeSVG} alt="Sockbase Logotype" /></StyledHeader>
reactとstyledのコンポーネントが混在するところだとどちらのオブジェクトを参照しているかわからなくなるので Styled-prefix をつけてます

2023-03-03 15:10 UTC, TinyKitten requested changes

2023-03-03 17:48 UTC, 10mocy commented on packages/client/src/assets/logotype.svg
> +<svg id="_レイヤー_1" data-name="レイヤー 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 2168 374">
イラレ書き出したやつそのまま使ってたわ

2023-03-04 04:32 UTC, TinyKitten approved these changes
えらいっ

2023-03-05 09:21 UTC, merged