Feature/#6.circle application
sockbase/Sockbase pull request #24
Opened 2023-03-02 07:47 UTC by 10mocy

2023-03-05 15:50 UTC, 10mocy commented on packages/client/src/components/Form/Help.tsx
> +  *:focus + & {
input以外の要素に対応する

2023-03-05 15:56 UTC, 10mocy commented on packages/client/src/components/Form/Help.tsx
> +  *:focus + & {
input以外の要素に対応する

2023-03-05 15:56 UTC, 10mocy commented on packages/client/src/components/Layout/Default/Header.tsx
> +const Header: React.FC = () => {
開発用に追加。どこかのタイミングで正式版に置き換える

2023-03-05 15:56 UTC, 10mocy commented on packages/client/src/components/pages/events/Application/Step1.tsx
> +const Step1: React.FC<Props> = (props) => {
割と巨大なのでどこかのタイミングでコンポーネントに切り分けたい

2023-03-05 15:56 UTC, 10mocy commented on packages/client/src/components/pages/events/Application/Step2.tsx
> +const Step2: React.FC<Props> = (props) => {
同じく

2023-03-05 15:56 UTC, 10mocy commented on packages/client/src/components/pages/events/Application/Step3.tsx
> +const Step3: React.FC<Props> = (props) => {
同じく

2023-03-05 15:56 UTC, 10mocy commented on packages/client/src/components/pages/events/Application/Step3.tsx
> +const Step3: React.FC<Props> = (props) => {
決済周りは別のチケットで実装

2023-03-05 15:56 UTC, 10mocy commented on packages/client/src/components/pages/events/Application/StepContainer.tsx
> +  ]
どこかのタイミングでsharedに移動させる

2023-03-05 15:56 UTC, 10mocy commented on packages/client/src/components/pages/events/Application/Step1.tsx
> +            <option>あいうえお</option>
仮置き

2023-03-05 15:56 UTC, 10mocy commented on packages/client/src/containers/static/PrivacyPolicy.tsx
> +const PrivacyPolicy: React.FC = () => {
仮作成

2023-03-15 10:10 UTC, TinyKitten requested changes
暇になったら続きレヴューする

2023-03-15 10:10 UTC, TinyKitten commented on packages/client/src/components/Form/Radio.tsx
> +
[nits]
スペースいらんと思う

2023-03-15 10:10 UTC, TinyKitten commented on packages/client/src/components/Layout/Default/Header.tsx
> +    } else if (user) {
[imo]
早期リターンしてるから`else`いらんと思う
あと`user`に`null`が入る予定もないなら`if`自体要らなくなる気がする

2023-03-15 10:10 UTC, TinyKitten commented on packages/client/src/components/Parts/Alert.tsx
> +      ? {
[want]
可能であれば三項演算子ネストしないで

2023-03-17 05:51 UTC, 10mocy commented on packages/client/src/@types/index.d.ts
> +  results: Array<{
自分もT[]使えるところはT[]使いたいけど、Standard ESLintに怒られるのでArray<T>使ってる

2023-03-17 05:53 UTC, 10mocy commented on packages/client/src/components/Form/Input.tsx
> +    boxShadow: '0 2px 5px #ff222288'
> カラーコード

- 今後のリファクタリングで対応

> 透明度HEX

- これよくわからないので教えて欲しい

2023-03-17 05:53 UTC, 10mocy commented on packages/client/src/components/Form/Radio.tsx
> +      {props.values.map(i => <StyledRadioItem key={`${props.name}-${i.value}`}>
イテレータの `i` にしてる。このあたりは宗教

2023-03-18 05:28 UTC, TinyKitten commented on packages/client/src/components/Form/Input.tsx
> +    boxShadow: '0 2px 5px #ff222288'
`#FF2222` なんか赤い色
`#FF222288` なんか赤い色(透明度53%~54%)
どこからとってきたんこの色

2023-03-18 05:30 UTC, TinyKitten commented on packages/client/src/components/Form/Radio.tsx
> +      {props.values.map(i => <StyledRadioItem key={`${props.name}-${i.value}`}>
iは一般的にインデックスを示すからやめて❤️

2023-03-28 03:11 UTC, 10mocy commented on packages/client/src/components/Layout/Default/Header.tsx
> +    } else if (user) {
そもそもこのファイルは開発フェーズでしか使わないので対応しない

2023-03-28 03:20 UTC, 10mocy commented on packages/client/src/components/Layout/Default/Header.tsx
開発用なので後で削除する

2023-03-28 03:20 UTC, 10mocy commented on packages/client/src/components/Layout/Default/Header.tsx
> +    } else if (user) {
そもそもこのファイルは開発フェーズでしか使わないので対応しない

2023-03-28 03:20 UTC, 10mocy commented on packages/client/src/components/Form/Input.tsx
> +    boxShadow: '0 2px 5px #ff222288'
透明度はそれっぽく書いてただけだった(その変換あるの知らなかった)
今後色変数まとめるのをするのでその際に一括して対応する。

2023-04-04 11:37 UTC, merged